name: release-please

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-please-version: latest   # or a specific >= 18.x version
          token: ${{ secrets.GITHUB_TOKEN }}
