name: release-please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          command: manifest
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          # Built-in token is fine for same-repo releases
          token: ${{ secrets.GITHUB_TOKEN }}
